// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketSystem.Api.Data;

#nullable disable

namespace TicketSystem.Api.Data.Migrations
{
    [DbContext(typeof(TicketSystemContext))]
    partial class TicketSystemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("TicketSystem.Api.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CompletionDeadline")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmissionTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompletionDeadline = new DateTime(2030, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "ticket1",
                            SubmissionTime = new DateTime(2024, 4, 25, 0, 43, 29, 449, DateTimeKind.Utc).AddTicks(9923)
                        },
                        new
                        {
                            Id = 2,
                            CompletionDeadline = new DateTime(2040, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "ticket2",
                            SubmissionTime = new DateTime(2024, 4, 25, 0, 43, 29, 449, DateTimeKind.Utc).AddTicks(9926)
                        },
                        new
                        {
                            Id = 3,
                            CompletionDeadline = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "ticket3",
                            SubmissionTime = new DateTime(2024, 4, 25, 0, 43, 29, 449, DateTimeKind.Utc).AddTicks(9927)
                        },
                        new
                        {
                            Id = 4,
                            CompletionDeadline = new DateTime(2023, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "ticket4",
                            SubmissionTime = new DateTime(2024, 4, 25, 0, 43, 29, 449, DateTimeKind.Utc).AddTicks(9928)
                        },
                        new
                        {
                            Id = 5,
                            CompletionDeadline = new DateTime(2060, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "ticket5",
                            SubmissionTime = new DateTime(2024, 4, 25, 0, 43, 29, 449, DateTimeKind.Utc).AddTicks(9928)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
